DELETE https://morning-earth-10869.herokuapp.com/api/persons/1

###
POST https://morning-earth-10869.herokuapp.com/api/persons/ HTTP/1.1
content-type: application/json

{
  "name": "Rocky Johnson",
  "number": "543-789999971" 
  
 }

###
 GET https://morning-earth-10869.herokuapp.com/api/persons/