DELETE http://localhost:3001/api/persons/600f42cfb59db31ce80cd938

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
  "name": "Rocky Johnson",
  "number": "543-789999971" 
  
 }

###
 GET http://localhost:3001/api/persons/

 